---
name: Smartverse Cloud
version: "0.5.2"
slug: smartverse-cloud
description: A Cloud connection of your Home Assistant to a Smartverse cloud and access to your Home Assistant instance
url: https://www.smartverse.ru/homeassistant-cloud-addon
startup: services
ingress: true
ingress_port: 0
ingress_stream: false
init: false
panel_icon: mdi:cloud
panel_title: Smartverse Cloud
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
hassio_api: false
hassio_role: default
homeassistant_api: false
host_network: false
audio: false
apparmor: true
host_dbus: false
map:
  - backup:rw
  - homeassistant_config:r
journald: true
options:
  username: ""
  password: ""
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  username: str
  password: password
image: "registry.gitlab.smartverse.ru/pub/addon-smartverse-cloud/addon-smartverse-cloud-{arch}"
